[package]
name = "apollo-composition"
version = "0.2.2"
license = "Elastic-2.0"
edition = "2021"
authors = ["Apollo Developers <opensource@apollographql.com>"]
description = "Internal package used to create Apollo products"
readme = "README.md"
repository = "https://github.com/apollographql/federation-rs/"

[dependencies]
apollo-compiler = { workspace = true }
apollo-federation = "=2.0.0-preview.4"
apollo-federation-types = { version = "0.15.2", path = "../apollo-federation-types", features = [
  "composition",
] }
either = "1.12.0"
