[package]
name = "apollo-composition"
version = "0.1.0"
license = "Elastic-2.0"
edition = "2021"
authors = ["Apollo Developers <opensource@apollographql.com>"]
description = "Internal package used to create Apollo products"
readme = "README.md"
repository = "https://github.com/apollographql/federation-rs/"

[dependencies]
apollo-compiler = "1.0.0-beta.20"
apollo-federation = "2.0.0-alpha.3"
apollo-federation-types = { version="0.14.0-alpha.0", path = "../apollo-federation-types" }
either = "1.12.0"